var ccb_resources = [
    {type:'ccbi', src:"scene_start_help-ip5.ccbi"},
    {type:'image', src:"bg1-ip5.png"},
    {type:'image', src:"bg3-ip5.png"},
    {type:'image', src:"bg1.png"},
    {type:'image', src:"btn2_up.png"},
    {type:'plist', src:"Fishall.plist"},
    {type:'image', src:"bg3.png"},
    {type:'ccbi', src:"scene_start.ccbi"},
    {type:'ccbi', src:"scene_game_pausemenu-ip5.ccbi"},
    {type:'plist', src:"Fishtales.plist"},
    {type:'ccbi', src:"scene_start-ip5.ccbi"},
    {type:'image', src:"btn1_dw.png"},
    {type:'ccbi', src:"scene_game_pausemenu.ccbi"},
    {type:'image', src:"bg2.png"},
    {type:'ccbi', src:"test.ccbi"},
    {type:'image', src:"bg2-ip5.png"},
    {type:'image', src:"btn2_dw.png"},
    {type:'image', src:"Fishall.png"},
    {type:'image', src:"Fishtales.png"},
    {type:'image', src:"btn1_up.png"},
    {type:'ccbi', src:"scene_start_help.ccbi"},
];
